version: "3.3"
services:
    config-grpc-srv:
      image: scfobao/micro_config-grpc-srv:latest
      build: ./config-grpc-srv
      ports:
        - "9600:9600"

      networks: 
        - micro-net
    auth:
      image: scfobao/micro_auth:latest
      build: ./auth
      environment:
         CONFIG_SERVER: 192.168.1.132
         CONFIG_SERVER_PORT: 9600
      networks: 
        - micro-net
    inventory-srv:
      image: scfobao/micro_inventory-srv:latest
      build: ./inventory-srv   
      environment:
         CONFIG_SERVER: 192.168.1.132
         CONFIG_SERVER_PORT: 9600  
      networks: 
        - micro-net    
    orders-srv:
      image: scfobao/micro_orders-srv:latest
      build: ./orders-srv 
      environment:
         CONFIG_SERVER: 192.168.1.132
         CONFIG_SERVER_PORT: 9600   
      networks: 
        - micro-net      
    payment-srv:
      image: scfobao/micro_payment-srv:latest
      build: ./payment-srv    
      environment:
         CONFIG_SERVER: 192.168.1.132
         CONFIG_SERVER_PORT: 9600
      networks: 
        - micro-net               
    user-srv:
      image: scfobao/micro_user-srv:latest
      build: ./user-srv      
      environment:
         CONFIG_SERVER: 192.168.1.132
         CONFIG_SERVER_PORT: 9600
      networks: 
        - micro-net             
    user-web:
      image: scfobao/micro_user-web:latest
      build: ./user-web   
      networks: 
        - micro-net    
      environment:
         CONFIG_SERVER: 192.168.1.132
         CONFIG_SERVER_PORT: 9600 
        
    payment-web:
      image: scfobao/micro_payment-web:latest
      build: ./payment-web
      environment:
         CONFIG_SERVER: 192.168.1.132
         CONFIG_SERVER_PORT: 9600
      networks: 
        - micro-net    
       
    orders-web:
      image: scfobao/micro_orders-web:latest
      build: ./orders-web 
      environment:
         CONFIG_SERVER: 192.168.1.132
         CONFIG_SERVER_PORT: 9600
      networks: 
        - micro-net

    micro:
      command: --registry=consul --registry_address=www.edaoduo.com:8500 --api_namespace=mu.micro.book.web api --handler=web  --address=:8080 
      image: microhq/micro:latest
      ports:
        - "8080:8080"
      networks: 
        - micro-net

    micro-web: 
      command: --registry=consul --registry_address=www.edaoduo.com:8500 web 
      image: microhq/micro:latest
      ports:
        - "8082:8082"
      networks: 
        - micro-net

networks: 
    micro-net:
      driver: overlay





