version: "3.3"
services:
    auth:
      image: scfobao/micro_auth
      build: ./auth
    inventory-srv:
      image: scfobao/micro_inventory_srv
      build: ./inventory-srv
    orders-srv:
      image: scfobao/micro_orders_srv
      build: ./orders-srv
    payment-srv:
      image: scfobao/micro_payment_srv
      build: ./payment-srv        
    user-srv:
      image: scfobao/micro_user_srv
      build: ./user-srv       
    user-web:
      image: scfobao/micro_user_web
      build: ./user-web
    payment-web:
      image: scfobao/micro_payment_web
      build: ./payment-web
    orders-web:
      image: scfobao/micro_orders_web
      build: ./orders-web
    micro:
      command: --registry=consul --registry_address=www.edaoduo.com:8500 --api_namespace=mu.micro.book.web api --handler=web  --address=:8080 
      image: microhq/micro:latest
      ports:
        - "8080:8080"

    micro-web: 
      command: --registry=consul --registry_address=www.edaoduo.com:8500 web 
      image: microhq/micro:latest
      ports:
        - "8082:8082"





